// const {Sequelize, DataTypes, type} = require('sequelize');
const Sequelize = require("sequelize");

const ScoresSchema = sequelize.define('Scores', {
      ticker: {type: DataTypes.STRING, primaryKey: true,},
      calcDate: {type: DataTypes.DATEONLY, primaryKey: true,},
      indexName: DataTypes.STRING,
      marketCap: DataTypes.STRING,
      currency: DataTypes.STRING,
      sector: DataTypes.STRING,
      industry: DataTypes.STRING,
      scoreFull: DataTypes.INTEGER,
      scoreLight: DataTypes.INTEGER,
      recommendFull: DataTypes.STRING,
      recommendLight: DataTypes.STRING,
      cap: DataTypes.STRING,
      financeStock: DataTypes.STRING,
      lastEarningstype: DataTypes.DATEONLY,
      "1roe": DataTypes.INTEGER,
      "2ebitMarge": DataTypes.INTEGER,
      "3eqRatio": DataTypes.INTEGER,
      "4peRatio": DataTypes.INTEGER,
      "5peRatioHist": DataTypes.INTEGER,
      "6rating": DataTypes.INTEGER,
      "7reaction": DataTypes.INTEGER,
      "8profitRevision": DataTypes.INTEGER,
      "9changePrice6M": DataTypes.INTEGER,
      "10changePrice1Y": DataTypes.INTEGER,
      "11priceMomentum:": DataTypes.INTEGER,
      "12monthReversal": DataTypes.INTEGER,
      "13profitGrowth": DataTypes.INTEGER,
      "1roeValue": DataTypes.FLOAT(12),
      "2ebitMargeValue": DataTypes.FLOAT(12),
      "3eqRatioValue": DataTypes.FLOAT(12),
      "4peRatioHistValue": DataTypes.FLOAT(12),
      "5peRatioValue": DataTypes.FLOAT(12),
      "6ratingValue": DataTypes.FLOAT(12),
      "7quartalReactionValue": DataTypes.FLOAT(12),
      "8profitRevisionValue": DataTypes.FLOAT(12),
      "9priceToday6MValue": DataTypes.FLOAT(12),
      "10priceToday1YValue": DataTypes.FLOAT(12),
      "13profitGrowthValue": DataTypes.FLOAT(12),
    })
  
  module.exports = mongoose.model('Scores', ScoresSchema)