module.exports = (sequelize, type) => {
    return sequelize.define('scores', {
      ticker: { type: type.STRING, primaryKey: true,},
      calcDate: { type: type.DATEONLY, primaryKey: true,},
      indexName: type.STRING,
      marketCap: type.STRING,
      currency: type.STRING,
      sector: type.STRING,
      industry: type.STRING,
      scoreFull: type.INTEGER,
      scoreLight: type.INTEGER,
      recommendFull: type.STRING,
      recommendLight: type.STRING,
      cap: type.STRING,
      financeStock: type.STRING,
      lastEarningstype: type.DATEONLY,
      1roe: type.INTEGER,
      2ebitMarge: type.INTEGER,
      3eqRatio: type.INTEGER,
      4peRatio: type.INTEGER,
      5peRatioHist: type.INTEGER,
      6rating: type.INTEGER,
      7reaction: type.INTEGER,
      8profitRevision: type.INTEGER,
      9changePrice6M: type.INTEGER,
      10changePrice1Y: type.INTEGER,
      11priceMomentum: type.INTEGER,
      12monthReversal: type.INTEGER,
      13profitGrowth: type.INTEGER,
      1roeValue: type.FLOAT(12),
      2ebitMargeValue: type.FLOAT(12),
      3eqRatioValue: type.FLOAT(12),
      4peRatioHistValue: type.FLOAT(12),
      5peRatioValue: type.FLOAT(12),
      6ratingValue: type.FLOAT(12),
      7quartalReactionValue: type.FLOAT(12),
      8profitRevisionValue: type.FLOAT(12),
      9priceToday6MValue: type.FLOAT(12),
      10priceToday1YValue: type.FLOAT(12),
      13profitGrowthValue: type.FLOAT(12),
    });
  };